### ISSUE TITLE
Error on ePub Export

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/anthologize#1]
First we were getting this error:

ePub export requires XSL support

It's been enabled on the server which cleared that, now but we are still getting this error

> [15-Jun-2015 16:09:30 UTC] PHP Fatal error:  require_once(): Failed opening required 'PEAR.php' (include_path='.:/usr/share/php:/usr/share/pear:/var/www/commons.hwdsb.on.ca/wordpress/wp-content/plugins/anthologize/templates/epub/pear_ext') in /var/www/commons.hwdsb.on.ca/wordpress/wp-content/plugins/anthologize/templates/epub/pear_ext/Archive.php on line 38

Victor (server tech) shared this when I mentioned the error: PEAR.php is in the same directory and readable so why isn’t it finding it?

/var/www/commons.hwdsb.on.ca/wordpress/wp-content/plugins/anthologize/templates/epub/pear_ext/PEAR.php

There is some admission of silliness in Archive.php:

/**
- To have access to PEAR::isError and PEAR::raiseError
- We should probably use lazy include and remove this inclusion...
  */
  require_once "PEAR.php";

You could try changing the line above to

require_once ( dirname(**FILE**) . “PEAR.php" );

Thoughts?

**Comment by r-a-y** [comment]
Changing the one line will not help as there are other calls in the `pear_ext` directory that use `require_once`.

Looking into it.

**Comment by r-a-y** [comment]
This should be resolved now.  I tested on sandbox and it appears to be working.

**Comment by mrjarbenne** [comment]
Confirmed. Thanks as always.
